### ISSUE TITLE
Clicking on the minimap should jump to that position

### ISSUE THREAD

**Issue by SamLeatherdale** [mcheung63/netbeans-minimap#10]
It would be great if the editor could jump to the line or general area you clicked on when you click on an area in the minimap.

**Comment by mcheung63** [comment]
Hi, this feature should be already implemented. You can click on minimap and the editor will scroll to there. Is this what you want? thanks

**Comment by SamLeatherdale** [comment]
Yes, that is it. It doesn't appear to work if the file's line length is greater than the number of lines specified in the "use low resolution image to prevent slow performance" box.

**Comment by mcheung63** [comment]
got it, fixing now, 1-2 days. Thanks 👍

**Comment by mcheung63** [comment]
It should be fixed, right?
