### ISSUE TITLE
Still showing version 2.3 on netbeans plugins list

### ISSUE THREAD

**Issue by KKAAKKEE** [mcheung63/netbeans-minimap#7]
As of 4/7/2017 netbeans plugin store still shows version 2.3

![screenshot from 2017-04-07 10-44-03](https://cloud.githubusercontent.com/assets/8016688/24812507/360a8fa2-1b7f-11e7-957f-e1b22d0f3d2b.png)

**Comment by mcheung63** [comment]
i just submitted 2.7 last night to netbeans plugins central, waiting for approval. Thanks
