### ISSUE TITLE
V2.7 makes impossible to open source files

### ISSUE THREAD

**Issue by 303tek** [mcheung63/netbeans-minimap#8]
After updating to V2.7, is impossible to open source files

NetBeans 8.2 with PHP extensions installed
Update Minimap from 2.3 to 2.7 via Plugin Updater
Try to open a source file (js,php,css, etc.)
Disabling Minimap restores IDE normal operation.

**Comment by mcheung63** [comment]
Thank you so much for reporting and late reply, because I just got the solution. Netbeans mailing list and forum are so quiet. I uploaded V2.8 and waiting for approve. Please try it and reply me it works or not, thanks

**Comment by mcheung63** [comment]
not fixed yet, still happen
